import { DaysOpenProps } from 'src/types/POIType';

export const defaultDays: DaysOpenProps[] = [
  {
    id: 1,
    value: 'monday',
    name: 'Lundi',
    isOpen: false,
    selected: false,
    hoursOpen: [],
    hoursClose: [],
  },
  {
    id: 2,
    value: 'tuesday',
    name: 'Mardi',
    isOpen: false,
    selected: false,
    hoursOpen: [],
    hoursClose: [],
  },
  {
    id: 3,
    value: 'wednesday',
    name: 'Mercredi',
    isOpen: false,
    selected: false,
    hoursOpen: [],
    hoursClose: [],
  },
  {
    id: 4,
    value: 'thursday',
    name: 'Jeudi',
    isOpen: false,
    selected: false,
    hoursOpen: [],
    hoursClose: [],
  },
  {
    id: 5,
    value: 'friday',
    name: 'Vendredi',
    isOpen: false,
    selected: false,
    hoursOpen: [],
    hoursClose: [],
  },
  {
    id: 6,
    value: 'saturday',
    name: 'Samedi',
    isOpen: false,
    selected: false,
    hoursOpen: [],
    hoursClose: [],
  },
  {
    id: 7,
    value: 'sunday',
    name: 'Dimanche',
    isOpen: false,
    selected: false,
    hoursOpen: [],
    hoursClose: [],
  },
];
